-- Sprint 2o.0 — Step 4.1 — Additive HR4 recoupling.
--
-- This is the ADDITIVE half of the marketing↔PSO decoupling. The
-- destructive half (drop legacy contact_id columns, enforce NOT NULL
-- on prospect_id) belongs to Step 5b which runs only after Step 5a
-- finishes the data migration that populates marketing_prospects
-- from client_contacts.
--
-- Three tables touched here:
--
--   1. email_send_attempts — contact_id has 0 non-null rows in live
--      Postgres today. Safe to drop the column outright and replace
--      with prospect_id immediately. Drizzle owns the new column;
--      this migration only removes the legacy FK + column so Drizzle
--      can install the new one without conflict.
--
--   2. contact_activities — 6,952 rows, 100% with non-null contact_id.
--      We add a NULLABLE prospect_id column with the same ON DELETE
--      CASCADE semantics. Old contact_id stays intact and enforced
--      until Step 5b backfills.
--
--   3. contact_tag_assignments — 3 rows, same shape. Add NULLABLE
--      prospect_id alongside existing contact_id.
--
-- Idempotency contract — every statement is a no-op when re-run on:
--   • Fresh DB (marketing_prospects created by Drizzle later in boot)
--   • Pre-2o.0 DB (legacy shape — contact_id columns present)
--   • Post-2o.0 DB (already added prospect_id columns)
--   • Mid-Step-5b DB (contact_id already dropped)
--
-- The FK from prospect_id → marketing_prospects(id) is added by
-- Drizzle when the schema is pushed, NOT by this migration. This is
-- the same pattern Step 1 used for migration 0009 — the migration
-- prepares the table shape, Drizzle owns the FK + index.

-- ─── 1. email_send_attempts: drop legacy contact_id ─────────────────
-- Drop the FK first (constraint name is auto-generated by Postgres,
-- so we discover it via pg_constraint and drop dynamically). Then
-- drop the column. Drizzle will install prospect_id on next push.
DO $$
DECLARE
  fk_name text;
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public'
      AND table_name='email_send_attempts'
      AND column_name='contact_id'
  ) THEN
    SELECT con.conname INTO fk_name
    FROM pg_constraint con
    JOIN pg_attribute a
      ON a.attrelid = con.conrelid AND a.attnum = ANY(con.conkey)
    WHERE con.contype = 'f'
      AND con.conrelid = 'public.email_send_attempts'::regclass
      AND a.attname = 'contact_id';
    IF fk_name IS NOT NULL THEN
      EXECUTE format('ALTER TABLE email_send_attempts DROP CONSTRAINT %I', fk_name);
    END IF;
    -- Indexes that include contact_id must be dropped first (Drizzle
    -- recreates them on push using the new prospect_id column).
    DROP INDEX IF EXISTS email_send_attempts_campaign_idx;
    DROP INDEX IF EXISTS email_send_attempts_sequence_idx;
    ALTER TABLE email_send_attempts DROP COLUMN contact_id;
  END IF;
END $$;

-- ─── 2. contact_activities: add nullable prospect_id ────────────────
-- ADD COLUMN IF NOT EXISTS keeps this idempotent. No FK installed
-- here — Drizzle owns the FK declaration so the schema is the single
-- source of truth.
ALTER TABLE contact_activities
  ADD COLUMN IF NOT EXISTS prospect_id varchar(36);

-- ─── 3. contact_tag_assignments: add nullable prospect_id ───────────
ALTER TABLE contact_tag_assignments
  ADD COLUMN IF NOT EXISTS prospect_id varchar(36);
