import { useState, useMemo, useEffect } from "react";
import { useUrlFilterState } from "@/lib/use-url-filter-state";
import { useQuery, useMutation } from "@tanstack/react-query";
import { ErrorState } from "@/components/shared/error-state";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { PageHelpLink } from "@/components/page-help-link";
import { PageBreadcrumbs } from "@/components/page-breadcrumbs";
import { useToast } from "@/hooks/use-toast";
import { Link } from "wouter";
import { formatMoney, formatDate } from "@/components/shared/format";
import type { GlAccount } from "@shared/schema";
import {
  BookMarked, Plus, Trash2, Calendar, ChevronDown, ChevronRight, Eye, X, Filter,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { useDocumentTitle } from "@/lib/use-document-title";

interface JournalLine {
  id: number;
  journalEntryId: number;
  accountId: number;
  debit: string;
  credit: string;
  memo: string | null;
}

interface JournalEntry {
  id: number;
  orgId: string;
  entryDate: string;
  memo: string | null;
  sourceType: string | null;
  sourceId: number | null;
  isAutoGenerated: boolean;
  createdAt: string;
  lines: JournalLine[];
}

interface FormLine {
  key: number;
  accountId: string;
  debit: string;
  credit: string;
  memo: string;
}

const SOURCE_COLORS: Record<string, { bg: string; text: string }> = {
  INVOICE: { bg: "rgba(59,130,246,0.1)", text: "#3b82f6" },
  PAYMENT: { bg: "rgba(34,197,94,0.1)", text: "#22c55e" },
  PAYOUT: { bg: "rgba(245,158,11,0.1)", text: "#f59e0b" },
  EXPENSE: { bg: "rgba(239,68,68,0.1)", text: "#ef4444" },
  Manual: { bg: "rgba(168,85,247,0.1)", text: "#a855f7" },
};

function fmtMoney(v: string | number) {
  return formatMoney(v, "USD");
}

function fmtDate(d: string) {
  return formatDate(d);
}

function fmt(d: Date) {
  return d.toISOString().split("T")[0];
}

function getSourceLink(sourceType: string | null, sourceId: number | null): string | null {
  if (!sourceType || !sourceId) return null;
  if (sourceType === "INVOICE") return `/invoices`;
  if (sourceType === "PAYMENT") return `/payments`;
  if (sourceType === "PAYOUT") return `/payouts`;
  if (sourceType === "EXPENSE") return `/expenses`;
  return null;
}

export default function GLJournalEntriesPage() {
  useDocumentTitle("Journal Entries");
  const { toast } = useToast();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [expandedEntries, setExpandedEntries] = useState<Set<number>>(new Set());

  const initialAccountId = typeof window !== "undefined"
    ? new URLSearchParams(window.location.search).get("accountId") || ""
    : "";

  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = now.getMonth();
  const hasAccountFilter = !!initialAccountId;
  const [jeFilters, setJeFilter, setJeFilters] = useUrlFilterState({
    accountId: "",
    startDate: hasAccountFilter ? `${yyyy}-01-01` : fmt(new Date(yyyy, mm, 1)),
    endDate: hasAccountFilter ? fmt(now) : fmt(new Date(yyyy, mm + 1, 0)),
    range: hasAccountFilter ? "ytd" : "this-month",
    source: "all",
  });
  const accountIdFilter = jeFilters.accountId;
  const startDate = jeFilters.startDate;
  const endDate = jeFilters.endDate;
  const activeQuick = jeFilters.range;
  const sourceFilter = jeFilters.source;
  const setAccountIdFilter = (v: string) => setJeFilter("accountId", v);
  const setStartDate = (v: string) => setJeFilter("startDate", v);
  const setEndDate = (v: string) => setJeFilter("endDate", v);
  const setActiveQuick = (v: string) => setJeFilter("range", v);
  const setSourceFilter = (v: string) => setJeFilter("source", v);

  const { data: entries = [], isLoading, isError, refetch } = useQuery<JournalEntry[]>({
    queryKey: ["/api/gl/journal-entries", startDate, endDate, sourceFilter, accountIdFilter],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (startDate) params.set("startDate", startDate);
      if (endDate) params.set("endDate", endDate);
      if (sourceFilter && sourceFilter !== "all") params.set("sourceType", sourceFilter);
      if (accountIdFilter) params.set("accountId", accountIdFilter);
      const resp = await fetch(`/api/gl/journal-entries?${params}`, { credentials: "include" });
      if (!resp.ok) throw new Error("Failed to load entries");
      return resp.json();
    },
  });

  const { data: accounts = [] } = useQuery<GlAccount[]>({
    queryKey: ["/api/gl/accounts"],
  });

  const accountMap = useMemo(() => {
    const m = new Map<number, GlAccount>();
    for (const a of accounts) m.set(a.id, a);
    return m;
  }, [accounts]);

  const toggleEntry = (id: number) => {
    setExpandedEntries(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const applyQuick = (key: string) => {
    if (key === "custom") {
      setActiveQuick(key);
      return;
    }
    const range = getQuickRange(key);
    setJeFilters({ range: key, startDate: range.startDate, endDate: range.endDate });
  };

  return (
    <div className="px-6 lg:px-8 xl:px-10 py-6 space-y-6">
      <PageBreadcrumbs
        page="Journal Entries"
        showDashboard={false}
        items={[{ label: "Accounting", href: "/accounting", testId: "link-breadcrumb-accounting" }]}
      />
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ background: "linear-gradient(135deg, rgba(var(--lux-accent-rgb),0.15) 0%, rgba(var(--lux-accent-rgb),0.05) 100%)" }}>
            <BookMarked className="w-6 h-6" style={{ color: "var(--lux-accent)" }} />
          </div>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold tracking-tight" style={{ color: "var(--lux-text)" }} data-testid="text-page-title">
                Journal Entries
              </h1>
              <PageHelpLink />
            </div>
            <p className="text-sm mt-0.5" style={{ color: "var(--lux-text-muted)" }}>
              {entries.length} entr{entries.length !== 1 ? "ies" : "y"}
            </p>
          </div>
        </div>
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogTrigger asChild>
            <Button size="sm" className="text-white" data-testid="button-new-journal-entry" style={{ background: "var(--gradient-brand)" }}>
              <Plus className="w-4 h-4 mr-1.5" />
              New Journal Entry
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto" style={{ background: "var(--lux-surface)", borderColor: "var(--lux-border)" }}>
            <DialogHeader>
              <DialogTitle style={{ color: "var(--lux-text)" }}>New Journal Entry</DialogTitle>
            </DialogHeader>
            <JournalEntryForm
              accounts={accounts}
              onSuccess={() => {
                setDialogOpen(false);
                queryClient.invalidateQueries({ queryKey: ["/api/gl/journal-entries"] });
                toast({ title: "Journal entry created" });
              }}
            />
          </DialogContent>
        </Dialog>
      </div>

      <div className="rounded-xl border-0 p-4 space-y-3" style={{ background: "var(--lux-surface)", boxShadow: "var(--lux-card-shadow)" }}>
        <div className="flex items-center gap-2 flex-wrap">
          <Calendar className="w-4 h-4" style={{ color: "var(--lux-text-muted)" }} />
          <span className="text-sm font-medium" style={{ color: "var(--lux-text-secondary)" }}>Period:</span>
          {[
            { key: "this-month", label: "This Month" },
            { key: "last-quarter", label: "Last Quarter" },
            { key: "ytd", label: "Year to Date" },
            { key: "last-year", label: "Last Year" },
            { key: "custom", label: "Custom" },
          ].map(q => (
            <Button
              key={q.key}
              variant={activeQuick === q.key ? "default" : "outline"}
              size="sm"
              style={activeQuick === q.key ? { background: "var(--gradient-brand)" } : { borderColor: "var(--lux-border)", color: "var(--lux-text)" }}
              className={`h-7 text-xs ${activeQuick === q.key ? "text-white" : ""}`}
              onClick={() => applyQuick(q.key)}
              data-testid={`button-filter-${q.key}`}
            >
              {q.label}
            </Button>
          ))}
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-2">
            <label className="text-xs font-medium" style={{ color: "var(--lux-text-muted)" }}>From</label>
            <Input
              type="date"
              value={startDate}
              onChange={(e) => { setStartDate(e.target.value); setActiveQuick("custom"); }}
              className="w-40 h-8 text-sm"
              data-testid="input-start-date"
            />
          </div>
          <div className="flex items-center gap-2">
            <label className="text-xs font-medium" style={{ color: "var(--lux-text-muted)" }}>To</label>
            <Input
              type="date"
              value={endDate}
              onChange={(e) => { setEndDate(e.target.value); setActiveQuick("custom"); }}
              className="w-40 h-8 text-sm"
              data-testid="input-end-date"
            />
          </div>
          <div className="flex items-center gap-2">
            <label className="text-xs font-medium" style={{ color: "var(--lux-text-muted)" }}>Source</label>
            <Select value={sourceFilter} onValueChange={setSourceFilter}>
              <SelectTrigger className="w-36 h-8 text-sm" data-testid="select-source-filter">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Sources</SelectItem>
                <SelectItem value="INVOICE">Invoice</SelectItem>
                <SelectItem value="PAYMENT">Payment</SelectItem>
                <SelectItem value="PAYOUT">Payout</SelectItem>
                <SelectItem value="EXPENSE">Expense</SelectItem>
              </SelectContent>
            </Select>
          </div>
          {accountIdFilter && (() => {
            const acct = accountMap.get(parseInt(accountIdFilter));
            return (
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium" style={{ background: "rgba(var(--lux-accent-rgb),0.12)", color: "var(--lux-accent)" }} data-testid="badge-account-filter">
                <Filter className="w-3 h-3" />
                <span>Account: {acct ? `${acct.accountNumber} — ${acct.name}` : `#${accountIdFilter}`}</span>
                <button
                  className="ml-1 p-0.5 rounded-full hover:bg-black/10 dark:hover:bg-white/10"
                  onClick={() => { setAccountIdFilter(""); }}
                  data-testid="button-clear-account-filter"
                  aria-label="Clear account filter"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            );
          })()}
        </div>
      </div>

      <div className="rounded-xl border-0 overflow-hidden" style={{ background: "var(--lux-surface)", boxShadow: "var(--lux-card-shadow)" }}>
        <Table>
          <TableHeader>
            <TableRow style={{ background: "var(--lux-table-header-bg)" }}>
              <TableHead className="w-8" />
              <TableHead className="w-[70px] text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>JE #</TableHead>
              <TableHead className="w-[100px] text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Date</TableHead>
              <TableHead className="text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Memo</TableHead>
              <TableHead className="w-[100px] text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Source</TableHead>
              <TableHead className="text-right w-[110px] text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Debit Total</TableHead>
              <TableHead className="text-right w-[110px] text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Credit Total</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isError ? (
              <TableRow>
                <TableCell colSpan={7}>
                  <ErrorState title="Failed to load journal entries" onRetry={refetch} />
                </TableCell>
              </TableRow>
            ) : isLoading ? (
              Array.from({ length: 5 }).map((_, i) => (
                <TableRow key={i}>
                  <TableCell colSpan={7}><div className="h-10 rounded animate-pulse" style={{ background: "var(--lux-border)" }} /></TableCell>
                </TableRow>
              ))
            ) : entries.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} className="text-center py-16">
                  <BookMarked className="w-10 h-10 mx-auto mb-3" style={{ color: "var(--lux-text-muted)" }} />
                  <p className="text-sm font-medium" style={{ color: "var(--lux-text-muted)" }}>No journal entries found</p>
                  <p className="text-xs mt-1" style={{ color: "var(--lux-text-muted)" }}>
                    Create a manual entry or let the system auto-generate them from invoices, payments, and expenses
                  </p>
                </TableCell>
              </TableRow>
            ) : (
              entries.map((entry) => {
                const isExpanded = expandedEntries.has(entry.id);
                const totalDebit = entry.lines.reduce((s, l) => s + (parseFloat(l.debit) || 0), 0);
                const totalCredit = entry.lines.reduce((s, l) => s + (parseFloat(l.credit) || 0), 0);
                const sourceLabel = entry.sourceType || "Manual";
                const sourceColor = SOURCE_COLORS[sourceLabel] || SOURCE_COLORS.Manual;
                const sourceLink = getSourceLink(entry.sourceType, entry.sourceId);

                return (
                  <TableRow
                    key={entry.id}
                    className="group"
                    data-testid={`row-journal-entry-${entry.id}`}
                    style={{ cursor: "pointer" }}
                    onClick={() => toggleEntry(entry.id)}
                  >
                    <TableCell colSpan={7} className="p-0">
                      <div>
                        <div className="flex items-center px-4 py-3 hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors">
                          <div className="w-8 flex-shrink-0">
                            {isExpanded
                              ? <ChevronDown className="w-4 h-4" style={{ color: "var(--lux-text-muted)" }} />
                              : <ChevronRight className="w-4 h-4" style={{ color: "var(--lux-text-muted)" }} />
                            }
                          </div>
                          <span className="w-[70px] flex-shrink-0 font-sans tabular-nums text-xs font-semibold" style={{ color: "var(--lux-text-muted)" }}>
                            JE-{entry.id}
                          </span>
                          <span className="w-[100px] flex-shrink-0 tabular-nums text-xs" style={{ color: "var(--lux-text-secondary)" }}>
                            {fmtDate(entry.entryDate)}
                          </span>
                          <span className="flex-1 text-sm truncate pr-4" style={{ color: "var(--lux-text)" }}>
                            {entry.memo || "-"}
                          </span>
                          <div className="w-[100px] flex-shrink-0">
                            {sourceLink ? (
                              <a
                                href={sourceLink}
                                onClick={(e) => e.stopPropagation()}
                                data-testid={`link-source-${entry.id}`}
                              >
                                <Badge
                                  variant="secondary"
                                  className="text-[10px] font-semibold hover:opacity-80 transition-opacity"
                                  style={{ background: sourceColor.bg, color: sourceColor.text, border: "none" }}
                                >
                                  {sourceLabel}
                                </Badge>
                              </a>
                            ) : (
                              <Badge
                                variant="secondary"
                                className="text-[10px] font-semibold"
                                style={{ background: sourceColor.bg, color: sourceColor.text, border: "none" }}
                              >
                                {sourceLabel}
                              </Badge>
                            )}
                          </div>
                          <span className="w-[110px] flex-shrink-0 text-right tabular-nums text-sm" style={{ color: "var(--lux-text)" }}>
                            {fmtMoney(totalDebit)}
                          </span>
                          <span className="w-[110px] flex-shrink-0 text-right tabular-nums text-sm" style={{ color: "var(--lux-text)" }}>
                            {fmtMoney(totalCredit)}
                          </span>
                        </div>
                        {isExpanded && (
                          <div style={{ background: "var(--lux-bg)", borderTop: "1px solid var(--lux-border)" }}>
                            <table className="w-full text-sm">
                              <thead>
                                <tr style={{ borderBottom: "1px solid var(--lux-border)" }}>
                                  <th className="text-left px-4 py-2 pl-14 text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Account</th>
                                  <th className="text-left px-4 py-2 text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Memo</th>
                                  <th className="text-right px-4 py-2 text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Debit</th>
                                  <th className="text-right px-4 py-2 text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Credit</th>
                                </tr>
                              </thead>
                              <tbody>
                                {entry.lines.map((line, li) => {
                                  const acct = accountMap.get(line.accountId);
                                  return (
                                    <tr
                                      key={line.id}
                                      style={{ borderBottom: li < entry.lines.length - 1 ? "1px solid var(--lux-border)" : "none" }}
                                    >
                                      <td className="px-4 py-2 pl-14 text-xs" style={{ color: "var(--lux-text)" }}>
                                        <span className="font-sans tabular-nums mr-2" style={{ color: "var(--lux-text-muted)" }}>{acct?.accountNumber || "?"}</span>
                                        {acct?.name || `Account #${line.accountId}`}
                                      </td>
                                      <td className="px-4 py-2 text-xs" style={{ color: "var(--lux-text-secondary)" }}>
                                        {line.memo || "-"}
                                      </td>
                                      <td className="px-4 py-2 text-right tabular-nums text-xs" style={{ color: parseFloat(line.debit) > 0 ? "var(--lux-text)" : "var(--lux-text-muted)" }}>
                                        {parseFloat(line.debit) > 0 ? fmtMoney(line.debit) : "-"}
                                      </td>
                                      <td className="px-4 py-2 text-right tabular-nums text-xs" style={{ color: parseFloat(line.credit) > 0 ? "var(--lux-text)" : "var(--lux-text-muted)" }}>
                                        {parseFloat(line.credit) > 0 ? fmtMoney(line.credit) : "-"}
                                      </td>
                                    </tr>
                                  );
                                })}
                              </tbody>
                            </table>
                          </div>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

function getQuickRange(key: string): { startDate: string; endDate: string } {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = now.getMonth();
  if (key === "this-month") {
    return { startDate: fmt(new Date(yyyy, mm, 1)), endDate: fmt(new Date(yyyy, mm + 1, 0)) };
  }
  if (key === "last-quarter") {
    const qStart = Math.floor(mm / 3) * 3;
    return { startDate: fmt(new Date(yyyy, qStart - 3, 1)), endDate: fmt(new Date(yyyy, qStart, 0)) };
  }
  if (key === "last-year") {
    return { startDate: `${yyyy - 1}-01-01`, endDate: `${yyyy - 1}-12-31` };
  }
  if (key === "ytd") {
    return { startDate: `${yyyy}-01-01`, endDate: fmt(now) };
  }
  return { startDate: "", endDate: "" };
}

let lineKeyCounter = 2;

function JournalEntryForm({ accounts, onSuccess }: { accounts: GlAccount[]; onSuccess: () => void }) {
  const { toast } = useToast();
  const [entryDate, setEntryDate] = useState(fmt(new Date()));
  const [memo, setMemo] = useState("");
  const [lines, setLines] = useState<FormLine[]>([
    { key: 0, accountId: "", debit: "", credit: "", memo: "" },
    { key: 1, accountId: "", debit: "", credit: "", memo: "" },
  ]);

  const sortedAccounts = useMemo(
    () => [...accounts].filter(a => a.isActive).sort((a, b) => parseInt(a.accountNumber) - parseInt(b.accountNumber)),
    [accounts],
  );

  const totalDebit = useMemo(() => lines.reduce((s, l) => s + (parseFloat(l.debit) || 0), 0), [lines]);
  const totalCredit = useMemo(() => lines.reduce((s, l) => s + (parseFloat(l.credit) || 0), 0), [lines]);
  const isBalanced = Math.abs(totalDebit - totalCredit) < 0.005 && totalDebit > 0;
  const difference = Math.abs(totalDebit - totalCredit);

  const updateLine = (key: number, field: keyof FormLine, value: string) => {
    setLines(prev => prev.map(l => l.key === key ? { ...l, [field]: value } : l));
  };

  const addLine = () => {
    setLines(prev => [...prev, { key: lineKeyCounter++, accountId: "", debit: "", credit: "", memo: "" }]);
  };

  const removeLine = (key: number) => {
    if (lines.length <= 2) return;
    setLines(prev => prev.filter(l => l.key !== key));
  };

  const createMutation = useMutation({
    mutationFn: (data: { entryDate: string; memo: string; lines: { accountId: number; debit: string; credit: string; memo: string }[] }) =>
      apiRequest("POST", "/api/gl/journal-entries", data),
    onSuccess: () => onSuccess(),
    onError: (err: any) => toast({ title: "Error", description: err.message, variant: "destructive" }),
  });

  const [previewOpen, setPreviewOpen] = useState(false);

  const getValidLines = () => lines.filter(l => l.accountId && (parseFloat(l.debit) > 0 || parseFloat(l.credit) > 0));

  const handlePreview = (e: React.FormEvent) => {
    e.preventDefault();
    const validLines = getValidLines();
    if (validLines.length < 2) {
      toast({ title: "At least 2 line items with amounts are required", variant: "destructive" });
      return;
    }
    setPreviewOpen(true);
  };

  const handleConfirmPost = () => {
    const validLines = getValidLines();
    createMutation.mutate({
      entryDate,
      memo,
      lines: validLines.map(l => ({
        accountId: parseInt(l.accountId),
        debit: (parseFloat(l.debit) || 0).toFixed(2),
        credit: (parseFloat(l.credit) || 0).toFixed(2),
        memo: l.memo,
      })),
    });
    setPreviewOpen(false);
  };

  return (
    <form onSubmit={handlePreview} className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <Label htmlFor="entryDate">Date</Label>
          <Input
            id="entryDate"
            type="date"
            value={entryDate}
            onChange={(e) => setEntryDate(e.target.value)}
            required
            data-testid="input-entry-date"
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="memo">Memo</Label>
          <Input
            id="memo"
            value={memo}
            onChange={(e) => setMemo(e.target.value)}
            placeholder="Description of this entry"
            data-testid="input-entry-memo"
          />
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label>Line Items</Label>
          <Button type="button" variant="outline" size="sm" onClick={addLine} data-testid="button-add-line">
            <Plus className="w-3.5 h-3.5 mr-1" />
            Add Line
          </Button>
        </div>
        <div className="rounded-lg border overflow-hidden" style={{ borderColor: "var(--lux-border)" }}>
          <table className="w-full text-sm">
            <thead>
              <tr style={{ background: "var(--lux-bg)", borderBottom: "1px solid var(--lux-border)" }}>
                <th className="text-left px-3 py-2 text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Account</th>
                <th className="text-left px-3 py-2 text-[11px] font-semibold uppercase tracking-wider w-28" style={{ color: "var(--lux-text-muted)" }}>Debit</th>
                <th className="text-left px-3 py-2 text-[11px] font-semibold uppercase tracking-wider w-28" style={{ color: "var(--lux-text-muted)" }}>Credit</th>
                <th className="text-left px-3 py-2 text-[11px] font-semibold uppercase tracking-wider" style={{ color: "var(--lux-text-muted)" }}>Memo</th>
                <th className="w-10" />
              </tr>
            </thead>
            <tbody>
              {lines.map((line, idx) => (
                <tr key={line.key} style={{ borderBottom: idx < lines.length - 1 ? "1px solid var(--lux-border)" : "none" }}>
                  <td className="px-3 py-2">
                    <Select value={line.accountId} onValueChange={(v) => updateLine(line.key, "accountId", v)}>
                      <SelectTrigger className="h-8 text-xs" data-testid={`select-line-account-${idx}`}>
                        <SelectValue placeholder="Select account" />
                      </SelectTrigger>
                      <SelectContent>
                        {sortedAccounts.map(a => (
                          <SelectItem key={a.id} value={String(a.id)}>
                            {a.accountNumber} - {a.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </td>
                  <td className="px-3 py-2">
                    <Input
                      type="number"
                      step="0.01"
                      min="0"
                      placeholder="0.00"
                      value={line.debit}
                      onChange={(e) => updateLine(line.key, "debit", e.target.value)}
                      className="h-8 text-xs tabular-nums w-28"
                      data-testid={`input-line-debit-${idx}`}
                    />
                  </td>
                  <td className="px-3 py-2">
                    <Input
                      type="number"
                      step="0.01"
                      min="0"
                      placeholder="0.00"
                      value={line.credit}
                      onChange={(e) => updateLine(line.key, "credit", e.target.value)}
                      className="h-8 text-xs tabular-nums w-28"
                      data-testid={`input-line-credit-${idx}`}
                    />
                  </td>
                  <td className="px-3 py-2">
                    <Input
                      placeholder="Line memo"
                      value={line.memo}
                      onChange={(e) => updateLine(line.key, "memo", e.target.value)}
                      className="h-8 text-xs"
                      data-testid={`input-line-memo-${idx}`}
                    />
                  </td>
                  <td className="px-3 py-2">
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7"
                      onClick={() => removeLine(line.key)}
                      disabled={lines.length <= 2}
                      data-testid={`button-remove-line-${idx}`}
                      aria-label="Remove line"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="rounded-lg border p-3 space-y-2" style={{ borderColor: "var(--lux-border)", background: "var(--lux-bg)" }}>
        <div className="flex items-center justify-between text-sm">
          <span style={{ color: "var(--lux-text-muted)" }}>Total Debits</span>
          <span className="tabular-nums font-semibold" style={{ color: "var(--lux-text)" }} data-testid="text-form-total-debits">{fmtMoney(totalDebit)}</span>
        </div>
        <div className="flex items-center justify-between text-sm">
          <span style={{ color: "var(--lux-text-muted)" }}>Total Credits</span>
          <span className="tabular-nums font-semibold" style={{ color: "var(--lux-text)" }} data-testid="text-form-total-credits">{fmtMoney(totalCredit)}</span>
        </div>
        <div className="border-t pt-2" style={{ borderColor: "var(--lux-border)" }}>
          <div className="flex items-center justify-between text-sm">
            <span className="font-semibold" style={{ color: isBalanced ? "#22c55e" : "#ef4444" }}>
              {isBalanced ? "Balanced" : "Difference"}
            </span>
            <span className="tabular-nums font-bold" style={{ color: isBalanced ? "#22c55e" : "#ef4444" }} data-testid="text-form-difference">
              {isBalanced ? fmtMoney(0) : fmtMoney(difference)}
            </span>
          </div>
        </div>
      </div>

      <Button
        type="submit"
        className={`w-full ${isBalanced ? "text-white" : ""}`}
        disabled={!isBalanced || createMutation.isPending}
        data-testid="button-submit-journal-entry"
        style={{ background: isBalanced ? "var(--gradient-brand)" : undefined }}
      >
        {createMutation.isPending ? "Saving..." : !isBalanced ? "Debits must equal Credits to save" : (
          <span className="flex items-center gap-2"><Eye className="w-4 h-4" /> Preview & Post</span>
        )}
      </Button>

      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent style={{ background: "var(--lux-surface)", borderColor: "var(--lux-border)", maxWidth: 560 }}>
          <DialogHeader>
            <DialogTitle style={{ color: "var(--lux-text)" }}>Review Journal Entry</DialogTitle>
          </DialogHeader>
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div><span style={{ color: "var(--lux-text-muted)" }}>Date:</span> <strong style={{ color: "var(--lux-text)" }}>{entryDate}</strong></div>
              {memo && <div className="col-span-2"><span style={{ color: "var(--lux-text-muted)" }}>Memo:</span> <span style={{ color: "var(--lux-text)" }}>{memo}</span></div>}
            </div>
            <div className="rounded-lg border overflow-hidden" style={{ borderColor: "var(--lux-border)" }}>
              <table className="w-full text-sm">
                <thead>
                  <tr style={{ background: "var(--lux-bg)" }}>
                    <th className="text-left px-3 py-2 font-medium" style={{ color: "var(--lux-text-muted)" }}>Account</th>
                    <th className="text-right px-3 py-2 font-medium" style={{ color: "var(--lux-text-muted)" }}>Debit</th>
                    <th className="text-right px-3 py-2 font-medium" style={{ color: "var(--lux-text-muted)" }}>Credit</th>
                  </tr>
                </thead>
                <tbody>
                  {getValidLines().map((l, i) => {
                    const acct = sortedAccounts.find(a => String(a.id) === l.accountId);
                    return (
                      <tr key={i} style={{ borderTop: "1px solid var(--lux-border)" }}>
                        <td className="px-3 py-2" style={{ color: "var(--lux-text)" }}>{acct ? `${acct.accountNumber} – ${acct.name}` : l.accountId}</td>
                        <td className="px-3 py-2 text-right tabular-nums" style={{ color: parseFloat(l.debit) > 0 ? "var(--lux-text)" : "var(--lux-text-muted)" }}>{parseFloat(l.debit) > 0 ? fmtMoney(parseFloat(l.debit)) : "—"}</td>
                        <td className="px-3 py-2 text-right tabular-nums" style={{ color: parseFloat(l.credit) > 0 ? "var(--lux-text)" : "var(--lux-text-muted)" }}>{parseFloat(l.credit) > 0 ? fmtMoney(parseFloat(l.credit)) : "—"}</td>
                      </tr>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr style={{ borderTop: "2px solid var(--lux-border)", background: "var(--lux-bg)" }}>
                    <td className="px-3 py-2 font-bold text-sm" style={{ color: "var(--lux-text)" }}>Totals</td>
                    <td className="px-3 py-2 text-right font-bold tabular-nums" style={{ color: "var(--lux-text)" }}>{fmtMoney(totalDebit)}</td>
                    <td className="px-3 py-2 text-right font-bold tabular-nums" style={{ color: "var(--lux-text)" }}>{fmtMoney(totalCredit)}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button variant="outline" onClick={() => setPreviewOpen(false)}>Edit</Button>
              <Button className="text-white" style={{ background: "var(--gradient-brand)" }} onClick={handleConfirmPost} disabled={createMutation.isPending} data-testid="button-confirm-post-je">
                {createMutation.isPending ? "Posting..." : "Post Entry"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </form>
  );
}
