import { db } from "../db";
import { eq, and, inArray, sql } from "drizzle-orm";
import { invoices, payments, teamMemberPayoutsV2, glJournalEntries, glJournalLines, glAccounts, orgs } from "@shared/schema";

async function backfillGL() {
  console.log("[backfill-gl] Starting GL backfill...\n");

  const allOrgs = await db.select().from(orgs);
  let totalInvoices = 0, totalPayments = 0, totalPayouts = 0;

  for (const org of allOrgs) {
    const orgId = org.id;
    console.log(`[backfill-gl] Processing org: ${org.name} (${orgId})`);

    const accounts = await db.select().from(glAccounts).where(eq(glAccounts.orgId, orgId));
    const acctMap = new Map(accounts.map(a => [a.accountNumber, a]));

    if (!acctMap.has("1200") || !acctMap.has("4000") || !acctMap.has("1000")) {
      console.log(`  Skipping org — missing required GL accounts (1200, 4000, 1000)`);
      continue;
    }

    const existingJEs = await db.select().from(glJournalEntries).where(eq(glJournalEntries.orgId, orgId));
    const postedRefs = new Set(existingJEs.filter(je => je.sourceRef).map(je => je.sourceRef!));

    const orgInvoices = await db.select().from(invoices)
      .where(and(eq(invoices.orgId, orgId), inArray(invoices.status, ["SENT", "PARTIAL", "PAID", "VOID"])));

    let orgInvCount = 0;
    for (const inv of orgInvoices) {
      if (inv.status === "VOID" && postedRefs.has(inv.id) && !postedRefs.has(`${inv.id}-void`)) {
        const origEntry = existingJEs.find(je => je.sourceRef === inv.id);
        if (origEntry) {
          const origLines = await db.select().from(glJournalLines).where(eq(glJournalLines.journalEntryId, origEntry.id));
          const voidRef = `${inv.id}-void`;
          const reversalLines = origLines.map(l => ({
            accountId: l.accountId,
            debit: l.credit,
            credit: l.debit,
            memo: `Reversal: Invoice #${inv.number} voided`,
          }));
          await db.transaction(async (tx) => {
            const [entry] = await tx.insert(glJournalEntries).values({
              orgId, entryDate: new Date().toISOString().split("T")[0],
              memo: `Reversal: Invoice #${inv.number} voided`,
              sourceType: "INVOICE_VOID", sourceId: null, sourceRef: voidRef,
              isAutoGenerated: true, isReversing: false, createdByUserId: null,
            }).returning();
            for (const line of reversalLines) {
              await tx.insert(glJournalLines).values({ orgId, journalEntryId: entry.id, accountId: line.accountId, debit: line.debit, credit: line.credit, memo: line.memo });
            }
          });
          postedRefs.add(voidRef);
          orgInvCount++;
        }
        continue;
      }

      if (postedRefs.has(inv.id)) continue;

      const invTotal = Number(inv.total) || 0;
      const invSubtotal = Number(inv.subtotal) || invTotal;
      const invTax = Number(inv.taxAmount) || 0;
      if (invTotal === 0) continue;

      const journalLines: { accountId: number; debit: string; credit: string; memo?: string }[] = [
        { accountId: acctMap.get("1200")!.id, debit: invTotal.toFixed(2), credit: "0.00", memo: "Accounts Receivable" },
        { accountId: acctMap.get("4000")!.id, debit: "0.00", credit: invSubtotal.toFixed(2), memo: "Service Revenue" },
      ];
      if (invTax > 0 && acctMap.has("2300")) {
        journalLines.push({ accountId: acctMap.get("2300")!.id, debit: "0.00", credit: invTax.toFixed(2), memo: "Sales Tax Payable" });
      }

      const entryDate = inv.issuedDate || new Date().toISOString().split("T")[0];
      await db.transaction(async (tx) => {
        const [entry] = await tx.insert(glJournalEntries).values({
          orgId,
          entryDate,
          memo: `Backfill: Invoice ${inv.number} sent`,
          sourceType: "INVOICE",
          sourceId: null,
          sourceRef: inv.id,
          isAutoGenerated: true,
          isReversing: false,
          createdByUserId: null,
        }).returning();

        for (const line of journalLines) {
          await tx.insert(glJournalLines).values({
            orgId,
            journalEntryId: entry.id,
            accountId: line.accountId,
            debit: line.debit,
            credit: line.credit,
            memo: line.memo,
          });
        }
      });

      postedRefs.add(inv.id);
      orgInvCount++;

      if (inv.status === "VOID") {
        const voidRef = `${inv.id}-void`;
        if (!postedRefs.has(voidRef)) {
          const reversalLines = journalLines.map(l => ({
            accountId: l.accountId,
            debit: l.credit,
            credit: l.debit,
            memo: `Reversal: Invoice #${inv.number} voided`,
          }));

          await db.transaction(async (tx) => {
            const [entry] = await tx.insert(glJournalEntries).values({
              orgId,
              entryDate: new Date().toISOString().split("T")[0],
              memo: `Reversal: Invoice #${inv.number} voided`,
              sourceType: "INVOICE_VOID",
              sourceId: null,
              sourceRef: voidRef,
              isAutoGenerated: true,
              isReversing: false,
              createdByUserId: null,
            }).returning();

            for (const line of reversalLines) {
              await tx.insert(glJournalLines).values({
                orgId,
                journalEntryId: entry.id,
                accountId: line.accountId,
                debit: line.debit,
                credit: line.credit,
                memo: line.memo,
              });
            }
          });

          postedRefs.add(voidRef);
        }
      }
    }
    totalInvoices += orgInvCount;
    console.log(`  Invoices backfilled: ${orgInvCount}`);

    const orgPayments = await db.select().from(payments).where(eq(payments.orgId, orgId));
    let orgPmtCount = 0;
    for (const pmt of orgPayments) {
      if (postedRefs.has(pmt.id)) continue;
      if (pmt.status === "VOIDED" || pmt.status === "REFUNDED") continue;

      const pmtAmt = Number(pmt.amount) || 0;
      if (pmtAmt === 0) continue;

      const inv = orgInvoices.find(i => i.id === pmt.invoiceId);
      const invNumber = inv?.number || "Unknown";

      await db.transaction(async (tx) => {
        const [entry] = await tx.insert(glJournalEntries).values({
          orgId,
          entryDate: pmt.date || new Date().toISOString().split("T")[0],
          memo: `Backfill: Payment on Invoice ${invNumber}`,
          sourceType: "PAYMENT",
          sourceId: null,
          sourceRef: pmt.id,
          isAutoGenerated: true,
          isReversing: false,
          createdByUserId: null,
        }).returning();

        await tx.insert(glJournalLines).values({
          orgId,
          journalEntryId: entry.id,
          accountId: acctMap.get("1000")!.id,
          debit: pmtAmt.toFixed(2),
          credit: "0.00",
          memo: "Cash received",
        });
        await tx.insert(glJournalLines).values({
          orgId,
          journalEntryId: entry.id,
          accountId: acctMap.get("1200")!.id,
          debit: "0.00",
          credit: pmtAmt.toFixed(2),
          memo: "Accounts Receivable reduced",
        });
      });

      postedRefs.add(pmt.id);
      orgPmtCount++;
    }
    totalPayments += orgPmtCount;
    console.log(`  Payments backfilled: ${orgPmtCount}`);

    const orgPayouts = await db.select().from(teamMemberPayoutsV2)
      .where(and(eq(teamMemberPayoutsV2.orgId, orgId), eq(teamMemberPayoutsV2.status, "COMPLETED")));
    let orgPayoutCount = 0;
    for (const po of orgPayouts) {
      if (postedRefs.has(po.id)) continue;

      const poAmt = Number(po.amount) || 0;
      if (poAmt === 0) continue;

      if (!acctMap.has("5100")) continue;

      await db.transaction(async (tx) => {
        const [entry] = await tx.insert(glJournalEntries).values({
          orgId,
          entryDate: po.payoutDate || new Date().toISOString().split("T")[0],
          memo: `Backfill: Payout ${po.id}`,
          sourceType: "PAYOUT",
          sourceId: null,
          sourceRef: po.id,
          isAutoGenerated: true,
          isReversing: false,
          createdByUserId: null,
        }).returning();

        await tx.insert(glJournalLines).values({
          orgId,
          journalEntryId: entry.id,
          accountId: acctMap.get("5100")!.id,
          debit: poAmt.toFixed(2),
          credit: "0.00",
          memo: "Team payout costs",
        });
        await tx.insert(glJournalLines).values({
          orgId,
          journalEntryId: entry.id,
          accountId: acctMap.get("1000")!.id,
          debit: "0.00",
          credit: poAmt.toFixed(2),
          memo: "Cash disbursed",
        });
      });

      postedRefs.add(po.id);
      orgPayoutCount++;
    }
    totalPayouts += orgPayoutCount;
    console.log(`  Payouts backfilled: ${orgPayoutCount}`);

    const arSubledger = await db.select({
      total: sql<string>`COALESCE(SUM(CASE WHEN ${invoices.status} != 'VOID' THEN (${invoices.total}::numeric - ${invoices.paidAmount}::numeric) ELSE 0 END), 0)`,
    }).from(invoices).where(and(eq(invoices.orgId, orgId), inArray(invoices.status, ["SENT", "PARTIAL", "PAID"])));

    const arAcct = acctMap.get("1200");
    let gl1200Balance = 0;
    if (arAcct) {
      const balResult = await db.select({
        balance: sql<string>`COALESCE(SUM(${glJournalLines.debit}::numeric - ${glJournalLines.credit}::numeric), 0)`,
      }).from(glJournalLines)
        .innerJoin(glJournalEntries, eq(glJournalLines.journalEntryId, glJournalEntries.id))
        .where(and(eq(glJournalEntries.orgId, orgId), eq(glJournalLines.accountId, arAcct.id)));
      gl1200Balance = Number(balResult[0]?.balance || 0);
    }

    const arTotal = Number(arSubledger[0]?.total || 0);
    const diff = Math.abs(arTotal - gl1200Balance);
    console.log(`  Reconciliation: AR sub-ledger=${arTotal.toFixed(2)}, GL 1200=${gl1200Balance.toFixed(2)}, diff=${diff.toFixed(2)}${diff > 0.01 ? " ⚠️ MISMATCH" : " ✅"}`);
  }

  console.log(`\n[backfill-gl] SUMMARY: invoices=${totalInvoices}, payments=${totalPayments}, payouts=${totalPayouts}`);
  process.exit(0);
}

backfillGL().catch(err => {
  console.error("[backfill-gl] Fatal error:", err);
  process.exit(1);
});
